/**
 * llms-full-unbind
 *
 * Unbind `llms-full.txt` into individual pages programmatically.
 * A specialized parser designed to extract pages from the monolithic `llms-full.txt` format.
 *
 * Supports multiple formats:
 * - llms_txt2ctx format: `<doc title="..." desc="...">content</doc>` (generated by llms_txt2ctx CLI)
 * - vitepress-plugin-llms format: Markdown pages separated by `---` (generated by vitepress-plugin-llms)
 * - mintlify format: Markdown pages with `# Title` followed by `Source: URL` (generated by Mintlify)
 */

// Re-export types
export type { Page, Format, StreamingParser } from "./types.ts";

// Import types and parsers
import type { Page, Format } from "./types.ts";
import {
  parseLlmsTxt2ctxFormat,
  LlmsTxt2ctxStreamingParser,
} from "./llms-txt2ctx.ts";
import {
  parseVitepressPluginLlmsFormat,
  VitepressPluginLlmsStreamingParser,
} from "./vitepress-plugin-llms.ts";
import { parseMintlifyFormat, MintlifyStreamingParser } from "./mintlify.ts";

/**
 * Detect the format of the content
 */
function detectFormat(content: string): Format {
  // Check for doc tags first (llms_txt2ctx format)
  if (/<doc\s+title="/.test(content)) {
    return "llms-txt2ctx";
  }
  // Check for mintlify format (# Title followed by Source: URL)
  // This pattern is used by Mintlify-generated llms-full.txt
  if (/^# .+\nSource:\s/.test(content)) {
    return "mintlify";
  }
  // Check for vitepress-plugin-llms format (markdown with --- separators)
  if (content.includes("\n---\n") || content.startsWith("---\n")) {
    return "vitepress-plugin-llms";
  }
  // Default to llms_txt2ctx format
  return "llms-txt2ctx";
}

/**
 * Parses the entire string synchronously and returns an array of pages.
 *
 * Automatically detects the format of the content:
 * - llms_txt2ctx format: `<doc title="..." desc="...">content</doc>` (generated by llms_txt2ctx CLI)
 * - vitepress-plugin-llms format: Markdown pages separated by `---` (generated by vitepress-plugin-llms)
 * - mintlify format: Markdown pages with `# Title` followed by `Source: URL` (generated by Mintlify)
 *
 * @param content - The full content of llms-full.txt
 * @returns An array of Page objects
 *
 * @example
 * ```typescript
 * import { unbind } from "llms-full-unbind";
 *
 * const response = await fetch("https://example.com/llms-full.txt");
 * const text = await response.text();
 * const pages = unbind(text);
 *
 * console.log(`Extracted ${pages.length} pages.`);
 * ```
 */
export function unbind(content: string): Page[] {
  const format = detectFormat(content);

  if (format === "vitepress-plugin-llms") {
    return parseVitepressPluginLlmsFormat(content);
  }

  if (format === "mintlify") {
    return parseMintlifyFormat(content);
  }

  return parseLlmsTxt2ctxFormat(content);
}

/**
 * Accepts a standard Web `ReadableStream` (returned by `fetch`) or any Async Iterable.
 * Yields pages as soon as they are parsed.
 *
 * Automatically detects the format of the content:
 * - llms_txt2ctx format: `<doc title="..." desc="...">content</doc>` (generated by llms_txt2ctx CLI)
 * - vitepress-plugin-llms format: Markdown pages separated by `---` (generated by vitepress-plugin-llms)
 * - MCP format: Markdown pages with `# Title` followed by `Source: URL`
 *
 * @param stream - A Web ReadableStream or AsyncIterable providing the content
 * @returns An AsyncIterable of Page objects
 *
 * @example
 * ```typescript
 * import { unbindStream } from "llms-full-unbind";
 *
 * const response = await fetch("https://example.com/llms-full.txt");
 *
 * if (!response.body) {
 *   throw new Error("Response body is empty");
 * }
 *
 * for await (const page of unbindStream(response.body)) {
 *   console.log(`Processed: ${page.title}`);
 * }
 * ```
 */
export async function* unbindStream(
  stream: ReadableStream<Uint8Array> | AsyncIterable<Uint8Array | string>,
): AsyncIterable<Page> {
  const textDecoder = new TextDecoder();
  let parser:
    | LlmsTxt2ctxStreamingParser
    | VitepressPluginLlmsStreamingParser
    | MintlifyStreamingParser
    | null = null;
  let formatDetectionBuffer = "";

  /**
   * Detect format and create appropriate parser
   */
  function createParser():
    | LlmsTxt2ctxStreamingParser
    | VitepressPluginLlmsStreamingParser
    | MintlifyStreamingParser {
    const format = detectFormat(formatDetectionBuffer);
    let newParser:
      | LlmsTxt2ctxStreamingParser
      | VitepressPluginLlmsStreamingParser
      | MintlifyStreamingParser;

    if (format === "vitepress-plugin-llms") {
      newParser = new VitepressPluginLlmsStreamingParser();
    } else if (format === "mintlify") {
      newParser = new MintlifyStreamingParser();
    } else {
      newParser = new LlmsTxt2ctxStreamingParser();
    }

    // Feed buffered data to parser
    newParser.append(formatDetectionBuffer);
    formatDetectionBuffer = "";
    return newParser;
  }

  /**
   * Process text chunk
   */
  function* processChunk(text: string): Generator<Page> {
    if (parser === null) {
      formatDetectionBuffer += text;

      // Need enough data to detect format
      if (formatDetectionBuffer.length >= 100) {
        parser = createParser();
        yield* parser.processBuffer();
      }
    } else {
      parser.append(text);
      yield* parser.processBuffer();
    }
  }

  // Handle ReadableStream
  if ("getReader" in stream) {
    const reader = stream.getReader();
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        const text = textDecoder.decode(value, { stream: true });
        yield* processChunk(text);
      }
    } finally {
      reader.releaseLock();
    }
  } else {
    // Handle AsyncIterable
    for await (const chunk of stream) {
      const text =
        typeof chunk === "string"
          ? chunk
          : textDecoder.decode(chunk, { stream: true });

      yield* processChunk(text);
    }
  }

  // Final flush
  const finalText = textDecoder.decode();
  if (finalText) {
    yield* processChunk(finalText);
  }

  // Handle case where format wasn't detected due to small content
  if (parser === null && formatDetectionBuffer) {
    parser = createParser();
  }

  if (parser !== null) {
    yield* parser.processBuffer();

    // Flush remaining content for parsers that need it
    if (
      parser instanceof VitepressPluginLlmsStreamingParser ||
      parser instanceof MintlifyStreamingParser
    ) {
      yield* parser.flush();
    }
  }
}
