/**
 * vitepress-plugin-llms format parser
 *
 * Parses the format generated by vitepress-plugin-llms: Markdown pages separated by `---`
 * Used by vuejs.org and similar projects using VitePress.
 */

import type { Page, StreamingParser } from "./types.ts";

/**
 * Extract title from H1 header in markdown content
 * Handles formats like "# Title" or "# Title {#anchor}"
 */
function extractH1Title(content: string): string {
  const lines = content.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("# ")) {
      let title = trimmed.slice(2).trim();
      // Remove anchor like {#anchor}
      const anchorIndex = title.lastIndexOf("{#");
      if (anchorIndex !== -1 && title.endsWith("}")) {
        title = title.slice(0, anchorIndex).trim();
      }
      return title;
    }
  }
  return "";
}

/**
 * Extract URL metadata from content
 */
function extractUrlMetadata(content: string): string | null {
  const lines = content.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("url:")) {
      return trimmed.slice(4).trim();
    }
  }
  return null;
}

/**
 * Parse a single markdown page and extract title and metadata
 */
export function parseMarkdownPage(pageContent: string): Page | null {
  const trimmed = pageContent.trim();
  if (!trimmed) {
    return null;
  }

  // Extract title from H1 header
  const title = extractH1Title(trimmed);

  // Extract URL metadata if present
  const metadata: Record<string, unknown> = {};
  const url = extractUrlMetadata(trimmed);
  if (url) {
    metadata.url = url;
  }

  return {
    title,
    content: trimmed,
    ...(Object.keys(metadata).length > 0 && { metadata }),
  };
}

/**
 * Parse vitepress-plugin-llms format content synchronously
 */
export function parseVitepressPluginLlmsFormat(content: string): Page[] {
  const pages: Page[] = [];

  // Split by --- separator
  const sections = content.split(/\n---\n/);

  for (const section of sections) {
    const page = parseMarkdownPage(section);
    if (page && (page.title || page.content)) {
      pages.push(page);
    }
  }

  return pages;
}

/**
 * Streaming parser for vitepress-plugin-llms format
 */
export class VitepressPluginLlmsStreamingParser implements StreamingParser {
  private buffer = "";

  private currentSection = "";

  /**
   * Process the buffer and return complete pages
   */
  public *processBuffer(): Generator<Page> {
    // Add buffer to current section
    this.currentSection += this.buffer;
    this.buffer = "";

    // Look for separator
    const separator = "\n---\n";
    let separatorIndex: number;

    while ((separatorIndex = this.currentSection.indexOf(separator)) !== -1) {
      const section = this.currentSection.slice(0, separatorIndex);
      this.currentSection = this.currentSection.slice(
        separatorIndex + separator.length,
      );

      const page = parseMarkdownPage(section);
      if (page && (page.title || page.content)) {
        yield page;
      }
    }
  }

  /**
   * Process final content in buffer
   */
  public *flush(): Generator<Page> {
    if (this.currentSection.trim()) {
      const page = parseMarkdownPage(this.currentSection);
      if (page && (page.title || page.content)) {
        yield page;
      }
    }
  }

  /**
   * Append data to the buffer
   */
  public append(data: string): void {
    this.buffer += data;
  }
}
