/**
 * `<doc>` tag based format parser
 *
 * Parses the `<doc>` tag based format: `<doc title="..." desc="...">content</doc>`
 * Generated by the [`llms_txt2ctx`](https://llmstxt.org/) CLI from the llms-txt package.
 * Used by [fastht.ml](https://fastht.ml/docs/llms-ctx-full.txt) and similar projects.
 */

import type { DetectResult } from "../types.ts";
import { TagBaseStreamingParser } from "./utils/tag-base.ts";

/**
 * Streaming parser for <doc> tag based format using tokenizer
 */
export class DocTagStreamingParser extends TagBaseStreamingParser {
  /**
   * Detect if the content matches <doc> tag based format
   */
  public static detect(lines: string[]): DetectResult {
    return TagBaseStreamingParser.detect(lines, "doc");
  }

  public constructor() {
    super("doc");
  }
}
