/**
 * Mintlify format tests
 *
 * Tests for the format generated by Mintlify: Markdown pages with `# Title` followed by `Source: URL`
 * https://www.mintlify.com/docs/ai/llmstxt
 */

import assert from "node:assert";
import { describe, it } from "node:test";
import { unbind, unbindStream, type Page } from "../../../src/index.ts";

/**
 * Helper function to create a ReadableStream from a string
 */
function stringToStream(
  str: string,
  chunkSize = 10,
): ReadableStream<Uint8Array> {
  const encoder = new TextEncoder();
  const bytes = encoder.encode(str);
  let offset = 0;

  return new ReadableStream({
    pull(controller) {
      if (offset >= bytes.length) {
        controller.close();
        return;
      }

      const chunk = bytes.slice(offset, offset + chunkSize);
      offset += chunkSize;
      controller.enqueue(chunk);
    },
  });
}

describe("unbind (mintlify format)", () => {
  it("should parse markdown-source format", () => {
    const content = `# Build an MCP client
Source: https://modelcontextprotocol.io/docs/develop/build-client

Get started building your own client that can integrate with all MCP servers.

## System Requirements

Before starting, ensure your system meets these requirements.
# Build an MCP server
Source: https://modelcontextprotocol.io/docs/develop/build-server

Get started building your own server to use in Claude for Desktop.

## What we'll be building

We'll build a server that exposes two tools.`;

    const pages = Array.from(unbind(content));

    assert.strictEqual(pages.length, 2);
    assert.strictEqual(pages[0].title, "Build an MCP client");
    assert.strictEqual(pages[1].title, "Build an MCP server");
    assert.deepStrictEqual(pages[0].metadata, {
      source: "https://modelcontextprotocol.io/docs/develop/build-client",
    });
    assert.deepStrictEqual(pages[1].metadata, {
      source: "https://modelcontextprotocol.io/docs/develop/build-server",
    });
    assert.ok(
      pages[0].content.includes("Get started building your own client"),
    );
    assert.ok(
      pages[1].content.includes("Get started building your own server"),
    );
  });

  it("should extract source URL from content", () => {
    const content = `# What is the Model Context Protocol (MCP)?
Source: https://modelcontextprotocol.io/docs/concepts/what-is-mcp

The Model Context Protocol (MCP) is an open standard.

## Overview

MCP enables AI applications.`;

    const pages = Array.from(unbind(content));

    assert.strictEqual(pages.length, 1);
    assert.strictEqual(
      pages[0].title,
      "What is the Model Context Protocol (MCP)?",
    );
    assert.deepStrictEqual(pages[0].metadata, {
      source: "https://modelcontextprotocol.io/docs/concepts/what-is-mcp",
    });
  });

  it("should handle multiple pages with various content", () => {
    const content = `# Architecture overview
Source: https://modelcontextprotocol.io/docs/concepts/architecture

MCP has a flexible architecture.

## Core Components

The core components include:
# Understanding MCP clients
Source: https://modelcontextprotocol.io/docs/concepts/clients

Learn about MCP clients.

## What is a client?

A client connects to servers.
# Understanding MCP servers
Source: https://modelcontextprotocol.io/docs/concepts/servers

Learn about MCP servers.

## What is a server?

A server provides capabilities.`;

    const pages = Array.from(unbind(content));

    assert.strictEqual(pages.length, 3);
    assert.strictEqual(pages[0].title, "Architecture overview");
    assert.strictEqual(pages[1].title, "Understanding MCP clients");
    assert.strictEqual(pages[2].title, "Understanding MCP servers");
  });

  it("should handle empty content gracefully", () => {
    const pages = Array.from(unbind(""));
    assert.strictEqual(pages.length, 0);
  });

  it("should handle content with only whitespace", () => {
    const pages = Array.from(unbind("   \n\n   \n"));
    assert.strictEqual(pages.length, 0);
  });
});

describe("unbindStream (mintlify format)", () => {
  it("should parse markdown-source format from stream", async () => {
    const content = `# Build an MCP client
Source: https://modelcontextprotocol.io/docs/develop/build-client

Get started building your own client.
# Build an MCP server
Source: https://modelcontextprotocol.io/docs/develop/build-server

Get started building your own server.`;

    const stream = stringToStream(content, 50);
    const pages: Page[] = [];

    for await (const page of unbindStream(stream)) {
      pages.push(page);
    }

    assert.strictEqual(pages.length, 2);
    assert.strictEqual(pages[0].title, "Build an MCP client");
    assert.strictEqual(pages[1].title, "Build an MCP server");
  });

  it("should handle small chunks", async () => {
    const content = `# First Page
Source: https://example.com/first

Content of first page.
# Second Page
Source: https://example.com/second

Content of second page.`;

    const stream = stringToStream(content, 5);
    const pages: Page[] = [];

    for await (const page of unbindStream(stream)) {
      pages.push(page);
    }

    assert.strictEqual(pages.length, 2);
  });

  it("should handle async iterable input", async () => {
    const content = `# Async Page
Source: https://example.com/async

Content here.`;

    /**
     * Generate string chunks asynchronously
     */
    async function* generateChunks(): AsyncIterable<string> {
      await Promise.resolve();
      yield content;
    }

    const pages: Page[] = [];
    for await (const page of unbindStream(generateChunks())) {
      pages.push(page);
    }

    assert.strictEqual(pages.length, 1);
    assert.strictEqual(pages[0].title, "Async Page");
  });

  it("should extract metadata from streamed content", async () => {
    const content = `# Tools
Source: https://modelcontextprotocol.io/specification/server/tools

Tools allow servers to expose executable functions.

## Data Types

### Tool

A tool definition includes name and description.`;

    const stream = stringToStream(content, 30);
    const pages: Page[] = [];

    for await (const page of unbindStream(stream)) {
      pages.push(page);
    }

    assert.strictEqual(pages.length, 1);
    assert.strictEqual(pages[0].title, "Tools");
    assert.deepStrictEqual(pages[0].metadata, {
      source: "https://modelcontextprotocol.io/specification/server/tools",
    });
  });
});

describe("format detection (mintlify)", () => {
  it("should detect mintlify format by Source line", () => {
    const content = `# Page Title
Source: https://example.com/page

Content here.`;

    const pages = Array.from(unbind(content));

    assert.strictEqual(pages.length, 1);
    assert.strictEqual(pages[0].title, "Page Title");
    assert.deepStrictEqual(pages[0].metadata, {
      source: "https://example.com/page",
    });
  });

  it("should not confuse markdown-separator with markdown-source", () => {
    // This has --- separators but also has Source: lines
    // The format detection should pick markdown-source due to the pattern
    const content = `# First Page
Source: https://example.com/first

Content
---
More content after separator`;

    const pages = Array.from(unbind(content));

    // Should be treated as markdown-source format (one page with --- in content)
    assert.strictEqual(pages.length, 1);
    assert.strictEqual(pages[0].title, "First Page");
    assert.ok(pages[0].content.includes("---"));
  });
});
